### ISSUE TITLE
博客挂了，可以修一下吗

### ISSUE THREAD

**Issue by yazawaniconii** [biaochenxuying/blog-vue-typescript#25]
开发者你好，我看到你项目的文档好像都写在博客了，但是博客我点不进去，希望能修一下。或者能发一下这个项目的api文档吗，不是很懂vue，但挺喜欢你这个博客模板的，想自己写一下后端对接

**Comment by biaochenxuying** [comment]
> 开发者你好，我看到你项目的文档好像都写在博客了，但是博客我点不进去，希望能修一下。或者能发一下这个项目的api文档吗，不是很懂vue，但挺喜欢你这个博客模板的，想自己写一下后端对接

你好 失效的文章链接都已经更新了哈
